layout_spectrum: 1
typography_spectrum: 0.1044776
color:
  saturation: 0.5684191
  lightness: 0.850612
  brandStrength: 0.939202
  brandColors:
    - '#1D548D'
    - '#85A6D3'
    - '#012350'
    - '#E2E6E7'
    - '#5F827C'
  rhythmicContrast: 0.6259357
name: Kevin Westby Media
